# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_code', models.CharField(default=None, max_length=16)),
                ('soldtoname', models.CharField(default=None, max_length=64)),
                ('bp_demand', models.FloatField(default=0)),
                ('bp_supply', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DemandChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_code', models.CharField(default=None, max_length=16)),
                ('soldtoname', models.CharField(default=None, max_length=64)),
                ('salesname', models.CharField(default=None, max_length=32)),
                ('monat', models.CharField(default=None, max_length=16)),
                ('akt_day', models.DateField()),
                ('last_umwteuro_amt', models.FloatField(default=0)),
                ('this_umwteuro_amt', models.FloatField(default=0)),
                ('diff_umwteuro', models.FloatField(default=0)),
                ('last_umwtpcs_amt', models.IntegerField(default=0)),
                ('this_umwtpcs_amt', models.IntegerField(default=0)),
                ('diff_umwtpcs', models.IntegerField(default=0)),
                ('diff_umwtpcs_percent', models.FloatField(default=0)),
                ('sc_diff_umwteuro_percent', models.FloatField(default=0)),
                ('alert_flag', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDiscrepancyAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.IntegerField(default=0)),
                ('clm_code', models.CharField(default=None, max_length=16)),
                ('soldtoname', models.CharField(default=None, max_length=64)),
                ('salesname', models.CharField(default=None, max_length=32)),
                ('monat', models.CharField(default=None, max_length=16)),
                ('wtpcs_amt', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0)),
                ('num_sd_diff', models.FloatField(default=0)),
                ('abs_num_sd_diff', models.FloatField(default=0)),
                ('percentage_deviation', models.FloatField(default=0)),
                ('upper_control_limit', models.FloatField(default=0)),
                ('lower_control_limit', models.FloatField(default=0)),
                ('alert_flag', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDiscrepancyGraphData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.IntegerField(default=0)),
                ('clm_code', models.CharField(default=None, max_length=16)),
                ('soldtoname', models.CharField(default=None, max_length=64)),
                ('salesname', models.CharField(default=None, max_length=32)),
                ('monat', models.CharField(default=None, max_length=16)),
                ('wtpcs_amt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_code', models.CharField(default='', max_length=16)),
                ('demand_up_threshold', models.FloatField(default=10)),
                ('demand_down_threshold', models.FloatField(default=50000)),
                ('supply_down_threshold', models.FloatField(default=93)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_code', models.CharField(default=None, max_length=16)),
                ('soldtoname', models.CharField(default=None, max_length=64)),
                ('salesname', models.CharField(default=None, max_length=32)),
                ('monat', models.CharField(default=None, max_length=32)),
                ('akt_day', models.DateField()),
                ('this_umwtpcs_3WPeriod', models.IntegerField(default=0)),
                ('last_umwtpcs_3WPeriod', models.IntegerField(default=0)),
                ('diff_umwtpcs_3WPeriod', models.IntegerField(default=0)),
                ('this_umatpcs_3WPeriod', models.IntegerField(default=0)),
                ('last_umatpcs_3WPeriod', models.IntegerField(default=0)),
                ('diff_umatpcs_3WPeriod', models.IntegerField(default=0)),
                ('sc_diff_umatpcs_percentage', models.FloatField(default=0)),
                ('alert_percentage', models.FloatField(default=0)),
                ('alert_flag', models.NullBooleanField()),
            ],
        ),
    ]
