# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplychangerecord',
            old_name='sc_diff_umatpcs_percentage',
            new_name='diff_umatpcs_3WPeriod_percent',
        ),
        migrations.RemoveField(
            model_name='supplychangerecord',
            name='alert_percentage',
        ),
    ]
