# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170617_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandchangerecord',
            name='diff_umwtpcs',
        ),
        migrations.RemoveField(
            model_name='demandchangerecord',
            name='diff_umwtpcs_percent',
        ),
        migrations.RemoveField(
            model_name='demandchangerecord',
            name='last_umwtpcs_amt',
        ),
        migrations.RemoveField(
            model_name='demandchangerecord',
            name='this_umwtpcs_amt',
        ),
    ]
