# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170522_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_code', models.CharField(default='', max_length=16)),
                ('sold_to_name', models.CharField(default='', max_length=16)),
                ('sales_name', models.CharField(default='', max_length=16)),
                ('monat', models.CharField(default='', max_length=16)),
                ('akt_day', models.DateField()),
                ('last_umwteuro_amt', models.FloatField(default=0)),
                ('this_umwteuro_amt', models.FloatField(default=0)),
                ('diff_umwteuro', models.FloatField(default=0)),
                ('last_umwtpcs_amt', models.IntegerField(default=0)),
                ('this_umwtpcs_amt', models.IntegerField(default=0)),
                ('diff_umwtpcs', models.IntegerField(default=0)),
                ('diff_umwtpcs_percent', models.FloatField(default=0)),
                ('sc_diff_umwteuro_percent', models.FloatField(default=0)),
                ('alert_type', models.CharField(default='', max_length=16)),
                ('aler_description', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderSnapshot',
        ),
    ]
