# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170617_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessperformance',
            name='bp_demand',
        ),
        migrations.AddField(
            model_name='businessperformance',
            name='bp_demand_next_quarter',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='businessperformance',
            name='bp_demand_this_quarter',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='businessperformance',
            name='bp_order',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessperformance',
            name='current_quarter',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='businessperformance',
            name='next_quarter',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
