# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170527_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdifference',
            name='sales_name',
        ),
        migrations.RemoveField(
            model_name='orderdifference',
            name='sold_to_name',
        ),
        migrations.AddField(
            model_name='orderdifference',
            name='salesname',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='orderdifference',
            name='soldtoname',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='orderdifference',
            name='alert_description',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='orderdifference',
            name='alert_type',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='orderdifference',
            name='clm_code',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='orderdifference',
            name='monat',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
