# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170527_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdifference',
            name='soldtoname',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
