# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20170527_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_code', models.CharField(default=None, max_length=16)),
                ('soldtoname', models.CharField(default=None, max_length=64)),
                ('bp', models.FloatField(default=0)),
                ('monat', models.CharField(default=None, max_length=16)),
            ],
        ),
    ]
