# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_businessperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessperformance',
            name='monat',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
