# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170527_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedThreeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldtoname', models.CharField(default=None, max_length=64)),
                ('salesname', models.CharField(default=None, max_length=32)),
                ('monat', models.CharField(default=None, max_length=16)),
                ('wtpcs_amt', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0)),
                ('alert_type', models.CharField(default=None, max_length=16)),
                ('alert_description', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='OrderDifference',
            new_name='NeedOneRecord',
        ),
    ]
