# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20170527_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessperformance',
            name='alert_type',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
