# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='demand_down_threshhold',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='demand_up_threshhold',
        ),
        migrations.AddField(
            model_name='profile',
            name='demand_down_threshold',
            field=models.FloatField(default=50000),
        ),
        migrations.AddField(
            model_name='profile',
            name='demand_up_threshold',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='supply_down_threshold',
            field=models.FloatField(default=93),
        ),
    ]
