# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20170601_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClmSoldtonamePairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_code', models.CharField(default='', max_length=16)),
                ('soldtoname', models.CharField(default=None, max_length=64)),
            ],
        ),
    ]
