# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_clmsoldtonamepairing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clmsoldtonamepairing',
            unique_together=set([('clm_code', 'soldtoname')]),
        ),
    ]
