# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20170601_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClmSoldtonamePairing',
            new_name='ClmSoldtoPair',
        ),
    ]
