# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20170601_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clm_code',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
