# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_needthreerecord_num_sd_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needthreerecord',
            name='alert_description',
        ),
        migrations.RemoveField(
            model_name='needthreerecord',
            name='alert_type',
        ),
        migrations.AddField(
            model_name='needthreerecord',
            name='alert_flag',
            field=models.NullBooleanField(),
        ),
    ]
