# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20170603_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessperformance',
            old_name='bp',
            new_name='bp_demand',
        ),
        migrations.RemoveField(
            model_name='businessperformance',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='businessperformance',
            name='monat',
        ),
        migrations.AddField(
            model_name='businessperformance',
            name='bp_supply',
            field=models.FloatField(default=0),
        ),
    ]
