# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20170603_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedTwoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_code', models.CharField(default=None, max_length=16)),
                ('soldtoname', models.CharField(default=None, max_length=64)),
                ('salesname', models.CharField(default=None, max_length=32)),
                ('monat', models.CharField(default=None, max_length=16)),
                ('akt_day', models.DateField()),
                ('this_umatpcs_3WPeriod', models.IntegerField(default=0)),
                ('last_umatpcs_3WPeriod', models.IntegerField(default=0)),
                ('diff_umatpcs_3WPeriod', models.IntegerField(default=0)),
                ('this_umatpcs_amt', models.IntegerField(default=0)),
                ('last_umatpcs_amt', models.IntegerField(default=0)),
                ('diff_umatpcs', models.IntegerField(default=0)),
                ('sc_diff_umatpcs_percentage', models.FloatField(default=0)),
                ('diff_umwtpcs_3WPeriod', models.IntegerField(default=0)),
                ('alert_percentage', models.FloatField(default=0)),
                ('alert_flag', models.NullBooleanField()),
            ],
        ),
    ]
