# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_delete_clmsoldtopair'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedOneRecord',
            new_name='DemandChangeRecord',
        ),
    ]
