# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20170604_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedTwoRecord',
            new_name='SupplyChangeRecord',
        ),
    ]
