# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20170604_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedThreeRecord',
            new_name='OrderDiscrepancyRecord',
        ),
    ]
