# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20170604_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdiscrepancyrecord',
            name='abs_num_sd_diff',
            field=models.FloatField(default=0),
        ),
    ]
