# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_orderdiscrepancyrecord_abs_num_sd_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplychangerecord',
            name='diff_umatpcs',
        ),
        migrations.RemoveField(
            model_name='supplychangerecord',
            name='last_umatpcs_amt',
        ),
        migrations.RemoveField(
            model_name='supplychangerecord',
            name='this_umatpcs_amt',
        ),
        migrations.AlterField(
            model_name='supplychangerecord',
            name='monat',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
