# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20170606_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychangerecord',
            name='last_umwtpcs_3WPeriod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplychangerecord',
            name='this_umwtpcs_3WPeriod',
            field=models.IntegerField(default=0),
        ),
    ]
