# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_code', models.CharField(default='', max_length=16)),
                ('sold_to_name', models.CharField(default='', max_length=16)),
                ('sales_name', models.CharField(default='', max_length=16)),
                ('monat', models.CharField(default='', max_length=16)),
                ('akt_day', models.DateField()),
            ],
        ),
    ]
